title: Cerberus Analytics Group # your name (or website title) here
logo: "/images/cerberus.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  We are a small group of white-hat hackers. We protect your reputation online and grow your business through white-hat techniques.
  <br><br>
  We are the secret weapon of a few small business owners who appreciate our unique skillset in white hat SEO, data science and social media mining and penetration testing.
  <br><br>
  <a href="https://www.linkedin.com/in/daynesorvisto/">Founder's LinkedIn Profile</a>
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
